Maybe this will do it

diff --git a/.github/workflows/development.yml b/.github/workflows/development.yml
--- a/.github/workflows/development.yml
+++ b/.github/workflows/development.yml
@@ -12,9 +12,18 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Debug
+        run: |
+          echo "Start time: $(date)"
+          echo "Debug information"
+          env
+          echo "End time: $(date)"
+
       - name: Checkout Repository
         uses: actions/checkout@v2
-
+        with:
+          token: ${{secrets.GH_TOKEN}}
+          
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
@@ -29,11 +38,27 @@ jobs:
       - name: Build
         run: npm run build
 
-      - name: Deploy to Development
-        if: github.event_name == 'push'
+      - name: Set Git Identity
         run: |
           git config user.name "Jeff Grafe"
           git config user.email "jagrafe94@gmail.com"
-          git checkout -B staging
-          git commit -am "Auto commit after successful deployment to Development"
-          git push https://$GITHUB_ACTOR:$GH_TOKEN@github.com/LucidApparition/LucidApparition.github.io.git staging
+
+      - name: Deploy to Development
+        if: github.event_name == 'push'
+        run: |
+          if [ "$GITHUB_REF" == "refs/heads/development" ]; then
+            if ! git log -1 --pretty=%B | grep -q 'Deploy to Development'; then
+              git checkout staging
+              
+              # Merge changes from development into staging
+              git merge development --no-edit
+              
+              # Check if there are changes before pushing to the next branch
+              if git diff --quiet; then
+                  echo "No changes to commit. Deployment to staging aborted."
+              else
+                git commit -am "Auto commit after successful deployment to Development"
+                git push https://$GITHUB_ACTOR:$GH_TOKEN@github.com/LucidApparition/LucidApparition.github.io.git staging
+              fi
+            fi
+          fi
